import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import axios from "axios";
import "antd/dist/reset.css";

import Sidebar from "../components/sidebar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Remote Code Execution Environment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Sidebar />
      </main>
    </>
  );
}
